### ISSUE TITLE
not authorized to perform: lambda:GetLayerVersion

### ISSUE THREAD

**Issue by ccfontes** [grav/aws-lumo-cljs-runtime#14]
I have the following issue deploying with runtime 17:
```
$ npx sls deploy
An error occurred: XXXLambdaFunction - User: arn:aws:iam::xxx:user/yyy is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-west-1:313836948343:layer:lumo-runtime:17 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: zzz).
```

Replicated issue with versions 9 through 16.

Deploys just fine with version 8: `arn:aws:lambda:eu-west-1:313836948343:layer:lumo-runtime:8`.

Ran cloudformation with the following permissions for version 17 to no avail:
```json
{
  "Effect": "Allow",
  "Action": "lambda:GetLayerVersion",
  "Resource": "arn:aws:lambda:eu-west-1:313836948343:layer:lumo-runtime:17"
}
```

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.1.0
     Serverless Version:        1.49.0
     Enterprise Plugin Version: 1.3.6
     Platform SDK Version:      2.1.0

**Comment by ccfontes** [comment]
Still having same issue as above deploying with root credentials.

Built lumo from latest, then published the layer to my own account and it worked. Here's the arn, for anyone experiencing the same issue, and needing a recent layer:
```
arn:aws:lambda:eu-west-1:016180002273:layer:lumo-runtime:1
```

PS - I have no idea why it works now.

**Comment by grav** [comment]
Hey Carlos! Thanks for the feedback. I'll look into why the published layers from version 9 do not work.

**Comment by grav** [comment]
@ccfontes I uploaded another version of the runtime, and checked that it worked from another AWS account. Could you confirm that it's working for you? Should be backwards compatible.

`arn:aws:lambda:eu-west-1:313836948343:layer:lumo-runtime:20`

**Comment by ccfontes** [comment]
Hey Mikkel, just confirmed and its deploying successfully. Thanks!

PS - Would be great to see an upgrade to Node v12/13. I.e., v12 stars up to 30% faster, and v13 also improves startup time further.

**Comment by grav** [comment]
@ccfontes Looking at https://github.com/anmonteiro/lumo, it seems it's been using NodeJS 12.2 for quite a while. Am I missing something? :-)

**Comment by ccfontes** [comment]
Brilliant.

Assumed node 10 was being used because I saw this line:
RUN curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -

Lumo ships with Node, forgot the detail.
