### ISSUE TITLE
The lumo runtime does not read from node_modules

### ISSUE THREAD

**Issue by arichiardi** [grav/aws-lumo-cljs-runtime#4]
Hi again!

So the problem is that when I include node modules in my lamdba function, the runtime cannot find them.

For instance I get:

```
Cannot find module 'ajv'
	 Function.Module._resolveFilename (internal/modules/cjs/loader.cljs:655:15)
	 Function.Module._load (internal/modules/cjs/loader.cljs:580:25)
	 Module.require (internal/modules/cjs/loader.cljs:711:19)
	 require (internal/modules/cjs/helpers.cljs:14:16)
	 Object.<anonymous> (/tmp/tmp.0BjCyWLnRv/test.cljs:2:24)
	 Module._compile (internal/modules/cjs/loader.cljs:805:30)
	 (Object.It)
	 (Object.lumo.repl.caching_node_eval)
	 (NO_SOURCE_FILE <embedded>:6030:9)
	 z (NO_SOURCE_FILE <embedded>:6031:22)
```

Let me try to explain the problem: because the `bootstrap` binary executes a file like

```
lumo /tmp/tmp.0BjCyWLnRr
```

It seems like `node_modules` is not read by `lumo` there.

This could be a `lumo` issue (or not) but it will require a change of the `bootstrap` script and maybe `runtime.cljs`.

**Comment by arichiardi** [comment]
I fixed it in my fork: https://github.com/arichiardi/aws-lumo-cljs-runtime/commit/9eb073434bb2426f73f579140dcc83dcd2001bcb

@grav let me know if you want me to push a PR or I can keep maintain my fork instead :wink:

**Comment by grav** [comment]
Awesome! Do make a PR, and I'll give it a look :-)

**Comment by arichiardi** [comment]
@grav given the previous PR is based on the one already open, I will wait for you to process that before working on rebasing and all that

**Comment by grav** [comment]
Ah yes, I did not notice that one before now. Been away from Github for a while :-)
I see there's plenty of activity both on Lumo and this project, which is very cool! I'll see if I can get some time to participate!

**Comment by grav** [comment]
Fixed in `master`
